src/objects/MyHttpRequest__b/MyHttpRequest__b.object-meta.xml
<CustomObject>
    <label>MyHttpRequest</label>
    <pluralLabel>MyHttpRequests</pluralLabel>
</CustomObject>

src/objects/MyHttpRequest__b/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <label>Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/MyHttpRequest__b/fields/ClassName__c.field-meta.xml
<CustomField>
    <fullName>ClassName__c</fullName>
    <label>ClassName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/MyHttpRequest__b/fields/FormData__c.field-meta.xml
<CustomField>
    <fullName>FormData__c</fullName>
    <label>FormData</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/MyHttpRequest__b/fields/Headers__c.field-meta.xml
<CustomField>
    <fullName>Headers__c</fullName>
    <label>Headers</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/MyHttpRequest__b/fields/LastAttemptDate__c.field-meta.xml
<CustomField>
    <fullName>LastAttemptDate__c</fullName>
    <label>LastAttemptDate</label>
    <type>DateTime</type>
</CustomField>

src/objects/MyHttpRequest__b/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Method</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/objects/MyHttpRequest__b/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Name</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/objects/MyHttpRequest__b/fields/NumberOfAttempts__c.field-meta.xml
<CustomField>
    <fullName>NumberOfAttempts__c</fullName>
    <label>NumberOfAttempts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/MyHttpRequest__b/fields/QueryParam__c.field-meta.xml
<CustomField>
    <fullName>QueryParam__c</fullName>
    <label>QueryParam</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/MyHttpRequest__b/fields/Repeat__c.field-meta.xml
<CustomField>
    <fullName>Repeat__c</fullName>
    <description>0 - do not repeat 1 - repeat</description>
    <label>Repeat</label>
    <precision>1</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/MyHttpRequest__b/fields/ResponseBody__c.field-meta.xml
<CustomField>
    <fullName>ResponseBody__c</fullName>
    <label>ResponseBody</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/MyHttpRequest__b/fields/StartRepeatDate__c.field-meta.xml
<CustomField>
    <fullName>StartRepeatDate__c</fullName>
    <label>StartRepeatDate</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

src/objects/MyHttpRequest__b/fields/StatusCode__c.field-meta.xml
<CustomField>
    <fullName>StatusCode__c</fullName>
    <label>StatusCode</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/MyHttpRequest__b/fields/Tik__c.field-meta.xml
<CustomField>
    <fullName>Tik__c</fullName>
    <label>Tik</label>
    <type>DateTime</type>
</CustomField>

src/objects/MyHttpRequest__b/fields/Tok__c.field-meta.xml
<CustomField>
    <fullName>Tok__c</fullName>
    <label>Tok</label>
    <type>DateTime</type>
</CustomField>

src/objects/MyHttpRequest__b/fields/Url__c.field-meta.xml
<CustomField>
    <fullName>Url__c</fullName>
    <label>Url</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

src/objects/MyHttpRequestSettings__mdt/MyHttpRequestSettings__mdt.object-meta.xml
<CustomObject>
    <label>MyHttpRequestSettings</label>
    <pluralLabel>MyHttpRequestSettings</pluralLabel>
</CustomObject>

src/objects/MyHttpRequestSettings__mdt/fields/RepeatInMin__c.field-meta.xml
<CustomField>
    <fullName>RepeatInMin__c</fullName>
    <label>RepeatInMin</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/classes/MyHttpRetryBatch.cls
public class MyHttpRetryBatch implements Database.Batchable<SObject>, Database.AllowsCallouts {
    private static final String NAME = 'MyHttpRetryBatch@';
    private static final Integer MAX_CALLOUTS_IN_SINGLE_TRANSACTION = 100;

    public List<MyHttpRequest__b> start(Database.BatchableContext context) {
        List<MyHttpRequest__b> repeatedRequests = [
            SELECT
                Url__c, Method__c, Name__c,
                FormData__c, QueryParam__c, Headers__c,
                Body__c, NumberOfAttempts__c, ClassName__c,
                LastAttemptDate__c, Repeat__c, StartRepeatDate__c
            FROM MyHttpRequest__b
            WHERE Repeat__c = 1 AND StartRepeatDate__c < :Datetime.now()
        ];
        return repeatedRequests;
    }

    public void execute(Database.BatchableContext context, List<MyHttpRequest__b> repeatedRequests) {
        List<MyHttpRequest__b> requestsToInsert = new List<MyHttpRequest__b>();
        List<MyHttpRequest__b> requestsToDelete = new List<MyHttpRequest__b>();

        for (MyHttpRequest__b request : repeatedRequests) {
            Type MyHttpRequest = Type.forName(request.ClassName__c);
            MyHttpRequest myReq = (MyHttpRequest)MyHttpRequest.newInstance();
            myReq.init(request);

            DateTime tik = Datetime.now();
            HTTPResponse response = myReq.executeSync();
            DateTime tok = Datetime.now();

            Boolean repeat = myReq.repeatCondition(response);

            MyHttpRequest__b insertRequest = new MyHttpRequest__b(
                Name__c = request.Name__c,
                NumberOfAttempts__c = request.NumberOfAttempts__c + 1,
                Url__c = request.Url__c,
                Method__c = request.Method__c,
                Tik__c = tik,
                Tok__c = tok,
                StartRepeatDate__c = request.StartRepeatDate__c,
                LastAttemptDate__c = tik,
                FormData__c = request.FormData__c,
                QueryParam__c = request.QueryParam__c,
                Headers__c = request.Headers__c,
                Body__c = request.Body__c,
                ClassName__c = request.ClassName__c,
                ResponseBody__c = response.getBody(),
                StatusCode__c = response.getStatusCode(),
                Repeat__c = repeat ? 1 : 0
            );

            MyHttpRequest__b deleteRequest = new MyHttpRequest__b(
                Name__c = request.Name__c,
                StartRepeatDate__c = request.StartRepeatDate__c,
                Repeat__c = request.Repeat__c
            );

            requestsToInsert.add(insertRequest);
            requestsToDelete.add(deleteRequest);
        }

        database.deleteImmediate(requestsToDelete);
        database.insertImmediate(requestsToInsert);
    }

    public void finish(Database.BatchableContext BC) {
        this.toSchedule();
    }

    public Id toSchedule() {
        List<MyHttpRequestSettings__mdt> settings = MyHttpRequestSettings__mdt.getAll().values();
        Integer afterTime = Integer.valueOf(settings[0].RepeatInMin__c);
        if (afterTime == null) {
            return null;
        }

        Datetime dt = Datetime.now();
        dt = dt.addMinutes(afterTime);

        return system.scheduleBatch(this, 'MyHttpBatch will start at: ' + dt.format('MM/dd/yyyy HH:mm:ss'), afterTime, MAX_CALLOUTS_IN_SINGLE_TRANSACTION);
    }
}