src/objects/MyHttpRequest__b/MyHttpRequest__b.object-meta.xml
<CustomObject>
    <label>MyHttpRequest</label>
    <pluralLabel>MyHttpRequests</pluralLabel>
</CustomObject>

src/objects/MyHttpRequest__b/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <label>Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/MyHttpRequest__b/fields/ClassName__c.field-meta.xml
<CustomField>
    <fullName>ClassName__c</fullName>
    <label>ClassName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/MyHttpRequest__b/fields/FormData__c.field-meta.xml
<CustomField>
    <fullName>FormData__c</fullName>
    <label>FormData</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/MyHttpRequest__b/fields/LastAttemptDate__c.field-meta.xml
<CustomField>
    <fullName>LastAttemptDate__c</fullName>
    <label>LastAttemptDate</label>
    <type>DateTime</type>
</CustomField>

src/objects/MyHttpRequest__b/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Method</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/objects/MyHttpRequest__b/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Name</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/objects/MyHttpRequest__b/fields/NumberOfAttempts__c.field-meta.xml
<CustomField>
    <fullName>NumberOfAttempts__c</fullName>
    <label>NumberOfAttempts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/MyHttpRequest__b/fields/QueryParam__c.field-meta.xml
<CustomField>
    <fullName>QueryParam__c</fullName>
    <label>QueryParam</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/MyHttpRequest__b/fields/Repeat__c.field-meta.xml
<CustomField>
    <fullName>Repeat__c</fullName>
    <description>0 - do not repeat 1 - repeat</description>
    <label>Repeat</label>
    <precision>1</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/MyHttpRequest__b/fields/ResponseBody__c.field-meta.xml
<CustomField>
    <fullName>ResponseBody__c</fullName>
    <label>ResponseBody</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/MyHttpRequest__b/fields/StartRepeatDate__c.field-meta.xml
<CustomField>
    <fullName>StartRepeatDate__c</fullName>
    <label>StartRepeatDate</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

src/objects/MyHttpRequest__b/fields/StatusCode__c.field-meta.xml
<CustomField>
    <fullName>StatusCode__c</fullName>
    <label>StatusCode</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/MyHttpRequest__b/fields/Tik__c.field-meta.xml
<CustomField>
    <fullName>Tik__c</fullName>
    <label>Tik</label>
    <type>DateTime</type>
</CustomField>

src/objects/MyHttpRequest__b/fields/Tok__c.field-meta.xml
<CustomField>
    <fullName>Tok__c</fullName>
    <label>Tok</label>
    <type>DateTime</type>
</CustomField>

src/objects/MyHttpRequest__b/fields/Url__c.field-meta.xml
<CustomField>
    <fullName>Url__c</fullName>
    <label>Url</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

src/classes/MyHttpRequestTest.cls
@isTest
public class MyHttpRequestTest {
    @isTest
    static void addDataTest() {
        MyHttpRequest myReq = new MyHttpRequest();
        myReq.addQueryParam('test', '1');
        myReq.addformData('test', '1');
        myReq.setBody('test');
        myReq.addHeader('content-type', 'application/json');
        myReq.setAfterSec(5 * 60);
        myReq.setUrl('https://test.url');
        myReq.setMethod('get');

        System.assertEquals(myReq.queryParam.get('test'), '1', 'queryParam is wrong.');
        System.assertEquals(myReq.formData.get('test'), '1', 'formData is wrong.');
        System.assertEquals(myReq.headers.get('content-type'), 'application/json', 'headers is wrong.');
        System.assertEquals(myReq.afterSec, 5 * 60, 'repeatTime is wrong.');
        System.assertEquals(myReq.body, 'test', 'body is wrong.');
        System.assertEquals(myReq.method, 'GET', 'method is wrong.');
        System.assertEquals(myReq.url, 'https://test.url', 'url is wrong.');
    }

    @isTest
    static void initRequestTest() {
        Test.setMock(HttpCalloutMock.class, new MyHttpMockFactory(200, 'test'));

        DateTime dt = Datetime.now();
        MyHttpRequest__b myReqToInit = new MyHttpRequest__b(
            Name__c = '0-test',
            NumberOfAttempts__c = 0,
            StartRepeatDate__c = dt,
            LastAttemptDate__c = dt,
            Url__c = 'https://test.url',
            Method__c = 'POST',
            Tik__c = dt,
            Tok__c = dt,
            FormData__c = 'test1=1&test2=2',
            QueryParam__c = 'test1=1&test2=2',
            Body__c = 'test',
            Repeat__c = 0,
            ClassName__c = 'MyHttpRequest',
            ResponseBody__c = 'test',
            StatusCode__c = 200
        );

        MyHttpRequest myReq = new MyHttpRequest();
        myReq.init(myReqToInit);
        HttpResponse response = myReq.executeSync();

        System.assertEquals(myReq.queryParam.get('test1'), '1', 'queryParam is wrong.');
        System.assertEquals(myReq.queryParam.get('test2'), '2', 'queryParam is wrong.');
        System.assertEquals(myReq.formData.get('test1'), '1', 'formData is wrong.');
        System.assertEquals(myReq.formData.get('test2'), '2', 'formData is wrong.');
        System.assertEquals(myReq.body, 'test', 'body is wrong.');
        System.assertEquals(myReq.method, 'POST', 'method is wrong.');
        System.assertEquals(myReq.url, 'https://test.url', 'url is wrong.');
        System.assertEquals(myReq.id, '0-test', 'id is wrong.');

        System.assertEquals(response.getStatusCode(), 200, 'status code is wrong.');
        System.assertEquals(response.getBody(), 'test', 'body is wrong.');
    }

    @isTest
    static void executeBatchTest() {
        Test.startTest();
        MyHttpRetryBatch batch = new MyHttpRetryBatch();
        batch.toSchedule();
        Test.stopTest();
    }

    @isTest
    static void executeSuccessTest() {
        Test.setMock(HttpCalloutMock.class, new MyHttpMockFactory(200, 'test'));

        MyHttpRequest myReq = new MyHttpRequest('https://test.url', 'POST');
        myReq.addformData('test', '1');
        myReq.addformData('test2', '1');
        myReq.addHeader('content-type', 'application/json');
        myReq.addQueryParam('test', '1');
        myReq.setBody('test');
        HttpResponse response = myReq.executeSync();

        Test.startTest();
        myReq.executeAsync();
        myReq.executeSchedule();
        myReq.executeSchedule(5);
        Test.stopTest();

        System.assertEquals(response.getStatusCode(), 200, 'status code is wrong.');
        System.assertEquals(response.getBody(), 'test', 'body is wrong.');
    }

    @isTest
    static void executeErorrTest() {
        Test.setMock(HttpCalloutMock.class, new MyHttpMockFactory(400, 'test'));

        MyHttpRequest myReq = new MyHttpRequest('https://test.url', 'POST');
        HttpResponse response = myReq.executeSync();

        Test.startTest();
        myReq.executeAsync();
        myReq.executeSchedule();
        myReq.executeSchedule(5);
        Test.stopTest();

        System.assertEquals(response.getStatusCode(), 400, 'status code is wrong.');
        System.assertEquals(response.getBody(), 'test', 'body is wrong.');
    }
}