src/objects/MyHttpRequest__b/MyHttpRequest__b.object-meta.xml
<CustomObject>
    <label>MyHttpRequest</label>
    <pluralLabel>MyHttpRequests</pluralLabel>
</CustomObject>

src/objects/MyHttpRequest__b/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <label>Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/MyHttpRequest__b/fields/ClassName__c.field-meta.xml
<CustomField>
    <fullName>ClassName__c</fullName>
    <label>ClassName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/MyHttpRequest__b/fields/FormData__c.field-meta.xml
<CustomField>
    <fullName>FormData__c</fullName>
    <label>FormData</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/MyHttpRequest__b/fields/Headers__c.field-meta.xml
<CustomField>
    <fullName>Headers__c</fullName>
    <label>Headers</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/MyHttpRequest__b/fields/LastAttemptDate__c.field-meta.xml
<CustomField>
    <fullName>LastAttemptDate__c</fullName>
    <label>LastAttemptDate</label>
    <type>DateTime</type>
</CustomField>

src/objects/MyHttpRequest__b/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Method</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/objects/MyHttpRequest__b/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Name</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/objects/MyHttpRequest__b/fields/NumberOfAttempts__c.field-meta.xml
<CustomField>
    <fullName>NumberOfAttempts__c</fullName>
    <label>NumberOfAttempts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/MyHttpRequest__b/fields/QueryParam__c.field-meta.xml
<CustomField>
    <fullName>QueryParam__c</fullName>
    <label>QueryParam</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/MyHttpRequest__b/fields/Repeat__c.field-meta.xml
<CustomField>
    <fullName>Repeat__c</fullName>
    <description>0 - do not repeat 1 - repeat</description>
    <label>Repeat</label>
    <precision>1</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/MyHttpRequest__b/fields/ResponseBody__c.field-meta.xml
<CustomField>
    <fullName>ResponseBody__c</fullName>
    <label>ResponseBody</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/MyHttpRequest__b/fields/StartRepeatDate__c.field-meta.xml
<CustomField>
    <fullName>StartRepeatDate__c</fullName>
    <label>StartRepeatDate</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

src/objects/MyHttpRequest__b/fields/StatusCode__c.field-meta.xml
<CustomField>
    <fullName>StatusCode__c</fullName>
    <label>StatusCode</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/MyHttpRequest__b/fields/Tik__c.field-meta.xml
<CustomField>
    <fullName>Tik__c</fullName>
    <label>Tik</label>
    <type>DateTime</type>
</CustomField>

src/objects/MyHttpRequest__b/fields/Tok__c.field-meta.xml
<CustomField>
    <fullName>Tok__c</fullName>
    <label>Tok</label>
    <type>DateTime</type>
</CustomField>

src/objects/MyHttpRequest__b/fields/Url__c.field-meta.xml
<CustomField>
    <fullName>Url__c</fullName>
    <label>Url</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

src/classes/MyHttpController.cls
public inherited sharing class MyHttpController {

    @AuraEnabled
    public static List<MyHttpRequest__b> getRequests(String fromDate, Boolean repeat) {
        DateTime dt;
        try {
            dt = DateTime.valueOfGMT(fromDate);
        } catch (Exception ex) {
            dt = DateTime.now();
        }

        Integer showRepeated = repeat ? 1 : 0;
        return [SELECT Body__c, ClassName__c, FormData__c, Headers__c,
                    LastAttemptDate__c, Method__c, Name__c, NumberOfAttempts__c,
                    QueryParam__c, Repeat__c, ResponseBody__c, StartRepeatDate__c,
                    StatusCode__c, Tik__c, Tok__c, Url__c
                FROM MyHttpRequest__b WHERE Repeat__c = :showRepeated AND StartRepeatDate__c > :dt LIMIT 40000];
    }

    @AuraEnabled
    public static void sendRequest(String jsonData) {
        MyHttpRequestWrapper requestWrapper = (MyHttpRequestWrapper) JSON.deserialize(jsonData, MyHttpRequestWrapper.class);
        MyHttpRequest myReq = new MyHttpRequest(requestWrapper.url, requestWrapper.method);

        for (Map<String,String> header : requestWrapper.headers) {
            if (!header.containsKey('name') || !header.containsKey('value')) { continue; }
            myReq.addHeader(header.get('name'), header.get('value'));
        }

        for (Map<String,String> queryParam : requestWrapper.queryParams) {
            if (!queryParam.containsKey('name') || !queryParam.containsKey('value')) { continue; }
            myReq.addQueryParam(queryParam.get('name'), queryParam.get('value'));
        }

        for (Map<String,String> formData : requestWrapper.formData) {
            if (!formData.containsKey('name') || !formData.containsKey('value')) { continue; }
            myReq.addFormData(formData.get('name'), formData.get('value'));
        }

        if (!String.isEmpty(requestWrapper.body)) {
            myReq.setBody(requestWrapper.body);
        }

        myReq.executeSync();
    }

    @AuraEnabled
    public static void stopBatch(Id jobID) {
        System.abortJob(jobID);
    }

    @AuraEnabled
    public static void runBatch(string type, Integer min, Boolean repeat) {
        MyHttpRetryBatch myHttpRetryBatch = new MyHttpRetryBatch(type, repeat);
        myHttpRetryBatch.toSchedule(min);
    }

    @AuraEnabled
    public static List<CronTrigger> getListOfBatches() {
        return [SELECT Id, CronJobDetail.Id, CronJobDetail.Name, CronJobDetail.JobType
                FROM CronTrigger
                WHERE CronJobDetail.Name LIKE 'MyHttpBatch (%'];
    }

    public class MyHttpRequestWrapper {
        String url;
        String method;
        String body;
        List<Map<String,String>> headers;
        List<Map<String,String>> queryParams;
        List<Map<String,String>> formData;
    }
}