src/objects/MyHttpRequest__b/MyHttpRequest__b.object-meta.xml
<CustomObject>
    <label>MyHttpRequest</label>
    <pluralLabel>MyHttpRequests</pluralLabel>
</CustomObject>

src/objects/MyHttpRequest__b/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <label>Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/MyHttpRequest__b/fields/ClassName__c.field-meta.xml
<CustomField>
    <fullName>ClassName__c</fullName>
    <label>ClassName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/MyHttpRequest__b/fields/FormData__c.field-meta.xml
<CustomField>
    <fullName>FormData__c</fullName>
    <label>FormData</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/MyHttpRequest__b/fields/Headers__c.field-meta.xml
<CustomField>
    <fullName>Headers__c</fullName>
    <label>Headers</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/MyHttpRequest__b/fields/LastAttemptDate__c.field-meta.xml
<CustomField>
    <fullName>LastAttemptDate__c</fullName>
    <label>LastAttemptDate</label>
    <type>DateTime</type>
</CustomField>

src/objects/MyHttpRequest__b/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Method</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/objects/MyHttpRequest__b/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Name</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/objects/MyHttpRequest__b/fields/NumberOfAttempts__c.field-meta.xml
<CustomField>
    <fullName>NumberOfAttempts__c</fullName>
    <label>NumberOfAttempts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/MyHttpRequest__b/fields/QueryParam__c.field-meta.xml
<CustomField>
    <fullName>QueryParam__c</fullName>
    <label>QueryParam</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/MyHttpRequest__b/fields/Repeat__c.field-meta.xml
<CustomField>
    <fullName>Repeat__c</fullName>
    <description>0 - do not repeat 1 - repeat</description>
    <label>Repeat</label>
    <precision>1</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/MyHttpRequest__b/fields/ResponseBody__c.field-meta.xml
<CustomField>
    <fullName>ResponseBody__c</fullName>
    <label>ResponseBody</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/MyHttpRequest__b/fields/StartRepeatDate__c.field-meta.xml
<CustomField>
    <fullName>StartRepeatDate__c</fullName>
    <label>StartRepeatDate</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

src/objects/MyHttpRequest__b/fields/StatusCode__c.field-meta.xml
<CustomField>
    <fullName>StatusCode__c</fullName>
    <label>StatusCode</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/MyHttpRequest__b/fields/Tik__c.field-meta.xml
<CustomField>
    <fullName>Tik__c</fullName>
    <label>Tik</label>
    <type>DateTime</type>
</CustomField>

src/objects/MyHttpRequest__b/fields/Tok__c.field-meta.xml
<CustomField>
    <fullName>Tok__c</fullName>
    <label>Tok</label>
    <type>DateTime</type>
</CustomField>

src/objects/MyHttpRequest__b/fields/Url__c.field-meta.xml
<CustomField>
    <fullName>Url__c</fullName>
    <label>Url</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

src/classes/MyHttpExecutor.cls
public class MyHttpExecutor implements Queueable, Database.AllowsCallouts {
    private MyHttpRequest myReq;
    private HttpRequest req;
    private String queryParam;
    private String formData;
    private String headers;

    public MyHttpExecutor(MyHttpRequest myReq) {
        this.myReq = myReq;
    }

    public void execute(QueueableContext context) {
        this.executeSync();
    }

    public Id executeAsync() {
       return System.enqueueJob(this);
    }

    public HTTPResponse executeSync() {
        this.prepare();
        Http http = new Http();

        this.myReq.beforeSend();

        DateTime tik = Datetime.now();
        HTTPResponse res = http.send(this.req);
        DateTime tok = Datetime.now();

        if (res.getStatusCode() > 299) {
            this.myReq.error(res);
        } else {
            this.myReq.success(res);
        }
        this.myReq.finish(res);

        if (this.myReq.id == null) {
            this.saveRequest(this.myReq.repeatCondition(res), tik, tok, res);
        }

        return res;
    }

    private void saveRequest(Boolean repeat, Datetime tik, Datetime tok, HTTPResponse res) {
        MyHttpRequest__b myReqToSave = new MyHttpRequest__b(
            Name__c = this.createId(),
            NumberOfAttempts__c = 0,
            StartRepeatDate__c = tik.addMinutes(this.myReq.startAfterInMin),
            LastAttemptDate__c = tik,
            Url__c = this.myReq.url,
            Method__c = this.myReq.method,
            Tik__c = tik,
            Tok__c = tok,
            FormData__c = this.formData,
            QueryParam__c = this.queryParam,
            Headers__c = this.headers,
            Body__c = this.myReq.body,
            Repeat__c = repeat ? 1 : 0,
            ClassName__c = String.valueOf(this.myReq).split(':')[0],
            ResponseBody__c = res.getBody(),
            StatusCode__c = res.getStatusCode()
        );


        if (!Test.isRunningTest()) {
            Database.SaveResult sr = database.insertImmediate(myReqToSave);
            if (!sr.isSuccess()) {
                System.debug(System.logginglevel.WARN, 'Cannot create request: ' + this.myReq.url + '; ' + sr.getErrors());
            }
        }
    }

    private String createId() {
        List<MyHttpRequest__b> lastRequest = [SELECT Name__c FROM MyHttpRequest__b LIMIT 1];

        Datetime dt = Datetime.now();
        String newId;
        if (lastRequest.isEmpty()) {
            newId = '0-' + String.valueOf(dt.getTime());
        } else {
            List<String> lastId = lastRequest[0].Name__c.split('-');
            newId = String.valueOf(Integer.valueOf(lastId[0]) + 1) + '-' + String.valueOf(dt.getTime());
        }

        return newId;
    }

    private void prepare() {
        HttpRequest req = new HttpRequest();
        req.setMethod(this.myReq.method);
        string url = this.myReq.url;

        this.headers = this.prepareData(this.myReq.headers);
        for (string key : this.myReq.headers.keySet()) {
            req.setHeader(key, this.myReq.headers.get(key));
        }

        this.queryParam = this.prepareData(this.myReq.queryParam);
        if (this.queryParam != null) {
            url += ('?' + this.queryParam);
        }

        this.formData = this.prepareData(this.myReq.formData);
        if (this.formData != null) {
            req.setHeader('Content-Type', 'application/x-www-form-urlencoded');
            req.setHeader('Content-Length', String.valueOf(formData.length()));
            req.setBody(this.formData);
        }

        if (this.myReq.body != null) {
            req.setBody(this.myReq.body);
        }

        req.setEndpoint(url);
        this.req = req;
    }

    private string prepareData(Map<String, String> data) {
        if (data.isEmpty()) {
            return null;
        }

        String stringData = '';
        Set<String> keySet = data.keySet();
        integer i = 0;
        integer last = keySet.size() - 1;
        for (string key : keySet) {
            String encoded = EncodingUtil.urlEncode(data.get(key), 'UTF-8');
            if (i == last) {
                stringData += (key + '=' + encoded);
            } else {
                stringData += (key + '=' + encoded + '&');
            }
            i++;
        }

        return stringData;
    }
}